spring:
  datasource:
    url: jdbc:mysql://vms275.cqtvbve6qkgo.us-east-2.rds.amazonaws.com:3306/vms275?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: admin
    password: vmscmpe275

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: UTC
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 957056747390-1ka3t3eenmqo9hd90f92gjpba2mn8rnm.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/api/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 1262649704198957
            clientSecret: d545258f4a0979db1d12dcdc53a5966b
            redirectUri: "{baseUrl}/api/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email
  mail:
    host: smtp.gmail.com
    port: 587
    username: cmpe275.vms@gmail.com
    password: vms@CMPE275
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUri: http://localhost:8080/
server:
  error:
    include-message: always
    include-binding-errors: always
